# encoding: utf-8
---
recipe:
  Rx: zhwiki-dict
  args:
    - version=20200701
  description: >-
    Install zhwiki dict from fcitx5-pinyin-zhwiki
download_files: >-
  # zhwiki.dict.yaml::https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.1/zhwiki-${version}.dict.yaml
install_files: >-
  # zhwiki.dict.yaml
