# encoding: utf-8
---
recipe:
  Rx: zhwiki-dict
  description: >-
    Install zhwiki dict from fcitx5-pinyin-zhwiki
download_files: >-
  zhwiki.dict.yaml::https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-20231205.dict.yaml
install_files: >-
  zhwiki.dict.yaml
